In [ ]:
import anndata as ad

import pandas as pd

adata = pd.read_parquet(r"E:\UIC_PHD\Python_projects\parquet_read\src\map_h5ad\centroids\lymph_node_centroid.parquet")


In [1]:
import scanpy as sc
ddata = sc.read_h5ad(r"F:\12_30_2025_test_azimuth_annotation\bladder_mapped\HBM236.JPVT.769.h5ad")

In [7]:
ref = sc.read_h5ad(r"C:\Users\Orangeeee\Downloads\5e1880b9-b680-4fe7-b929-51a18603ba99.h5ad")

In [22]:
ref

AnnData object with n_obs × n_vars = 25832 × 60606
    obs: 'donor_id', 'tissue_in_publication', 'anatomical_position', 'method', 'cdna_plate', 'library_plate', 'notes', 'cdna_well', 'assay_ontology_term_id', 'sample_id', 'replicate', '10X_run', 'ambient_removal', 'donor_method', 'donor_assay', 'donor_tissue', 'donor_tissue_assay', 'cell_type_ontology_term_id', 'compartment', 'broad_cell_class', 'free_annotation', 'manually_annotated', 'published_2022', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ercc', 'pct_counts_ercc', '_scvi_batch', '_scvi_labels', 'scvi_leiden_donorassay_full', 'ethnicity_original', 'scvi_leiden_res05_tissue', 'sample_number', 'suspension_type', 'tissue_type', 'disease_ontology_term_id', 'is_primary_data', 'tissue_ontology_term_id', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'development_stage_ontology_term_id', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'developm

In [55]:
g = ref.layers["decontXcounts"]

In [56]:
g[100:110, 200:210].toarray()

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    1,    0,    0],
       [   0,  293,    0,    0,    0,    0,    0,    0, 3807,    0],
       [   0,    0,    0,    0,    0,    0,   12,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    1],
       [   0,    0,    0,    0,    0,    0,    1,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  869,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int32)

In [2]:
ddata

AnnData object with n_obs × n_vars = 4826 × 32507
    obs: 'n_genes', 'n_counts', 'leiden', 'umap_density', 'azimuth_label', 'azimuth_id', 'predicted_CLID', 'predicted_label', 'cl_match_type', 'prediction_score', 'azimuth_label_tabula'
    var: 'hugo_symbol', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'annotation_metadata', 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'umap', 'umap_density_params'
    obsm: 'X_pca', 'X_umap', 'X_umap_proj', 'X_umap_proj_tabula'
    varm: 'PCs'
    layers: 'spliced', 'spliced_unspliced_sum', 'unscaled', 'unspliced'
    obsp: 'connectivities', 'distances'

In [52]:
f = ddata.layers["spliced_unspliced_sum"]

In [57]:
f.max()

np.float32(4164.0)

In [64]:
ff = f.toarray()


In [65]:
ff

array([[0. , 0. , 0. , ..., 0. , 1. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 1. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 3.3, 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ]],
      shape=(4826, 32507), dtype=float32)

In [3]:
ddata.obs["azimuth_label"]

AAACAGCCAGGTTACC    Ventricular Cardiomycoyte
AAACATGCAAGGAATC    Ventricular Cardiomycoyte
AAACATGCACAAAGCG    Ventricular Cardiomycoyte
AAACATGCACCACAAC    Ventricular Cardiomycoyte
AAACATGCACCTGGTG    Ventricular Cardiomycoyte
                              ...            
TTTGTGGCATGTTGCA                   Fibroblast
TTTGTGTTCAATCTCT    Ventricular Cardiomycoyte
TTTGTGTTCCGGGACT    Ventricular Cardiomycoyte
TTTGTGTTCCTGTTCA    Ventricular Cardiomycoyte
TTTGTTGGTGACATGC    Ventricular Cardiomycoyte
Name: azimuth_label, Length: 4826, dtype: category
Categories (16, object): ['Adipocyte', 'Arterial Endothelial', 'Atrial Cardiomyocyte', 'B', ..., 'Pericyte', 'Smooth Muscle', 'Venous Endothelial', 'Ventricular Cardiomycoyte']

In [4]:
ddata.obs["azimuth_label_tabula"]

AAACAGCCAGGTTACC          cardiac endothelial cell
AAACATGCAAGGAATC                smooth muscle cell
AAACATGCACAAAGCG    regular atrial cardiac myocyte
AAACATGCACCACAAC          cardiac endothelial cell
AAACATGCACCTGGTG          cardiac endothelial cell
                                 ...              
TTTGTGGCATGTTGCA          cardiac endothelial cell
TTTGTGTTCAATCTCT          cardiac endothelial cell
TTTGTGTTCCGGGACT          cardiac endothelial cell
TTTGTGTTCCTGTTCA          cardiac endothelial cell
TTTGTTGGTGACATGC          cardiac endothelial cell
Name: azimuth_label_tabula, Length: 4826, dtype: category
Categories (22, object): ['mesothelial cell', 'T cell', 'mast cell', 'smooth muscle cell', ..., 'regular atrial cardiac myocyte', 'fibroblast of cardiac tissue', 'cardiac endothelial cell', 'ventricular cardiac muscle cell']

In [6]:
import pandas as pd
# Extract the two columns into a new DataFrame
df_labels = ddata.obs[['azimuth_label', 'azimuth_label_tabula']].copy()

# Display the first few rows to verify
print(df_labels.head())

df_labels.to_csv("Heart_compare.csv")

                              azimuth_label            azimuth_label_tabula
AAACAGCCAGGTTACC  Ventricular Cardiomycoyte        cardiac endothelial cell
AAACATGCAAGGAATC  Ventricular Cardiomycoyte              smooth muscle cell
AAACATGCACAAAGCG  Ventricular Cardiomycoyte  regular atrial cardiac myocyte
AAACATGCACCACAAC  Ventricular Cardiomycoyte        cardiac endothelial cell
AAACATGCACCTGGTG  Ventricular Cardiomycoyte        cardiac endothelial cell


In [ ]:
import pandas as pd

# Returns the count of NaNs for every column
print(adata.isna().sum())

# Returns the TOTAL count of NaNs in the entire DataFrame
print(adata.isna().sum().sum())

In [24]:
adata.layers["scale_data"]

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 139336513 stored elements and shape (42036, 60606)>

In [30]:
X = adata.layers["scale_data"]

X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 139336513 stored elements and shape (42036, 60606)>

In [32]:
X.data[:10]     # non-zero values


array([0.02196305, 0.04784601, 0.9506134 , 0.00641976, 0.03269194,
       0.3483503 , 0.03797509, 0.08093058, 1.160462  , 0.18631282],
      dtype=float32)

In [35]:
bdata = ad.read_h5ad(r"F:\12_30_2025_test_azimuth_annotation\HBM355.DGKN.367.h5ad")


In [41]:
bdata

AnnData object with n_obs × n_vars = 1502 × 17561
    obs: 'n_genes', 'n_counts', 'leiden', 'umap_density'
    var: 'hugo_symbol', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'annotation_metadata', 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'umap', 'umap_density_params'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    layers: 'spliced', 'spliced_unspliced_sum', 'unscaled', 'unspliced'
    obsp: 'connectivities', 'distances'

In [38]:
bdata.X

array([[-0.24295834, -0.2900601 , -0.12636328, ..., -0.15901455,
        -0.05713207, -0.09340862],
       [-0.24295834, -0.2900601 , -0.12636328, ..., -0.15901455,
        -0.05713207, -0.09340862],
       [-0.24295834, -0.2900601 , -0.12636328, ..., -0.15901455,
        -0.05713207, -0.09340862],
       ...,
       [-0.24295834, -0.2900601 , -0.12636328, ..., -0.15901455,
        -0.05713207, -0.09340862],
       [ 1.3344812 , -0.2900601 , -0.12636328, ..., -0.15901455,
        -0.05713207, -0.09340862],
       [-0.24295834,  1.8532923 , -0.12636328, ..., -0.15901455,
        -0.05713207, -0.09340862]], shape=(1502, 17561), dtype=float32)

In [48]:
bdata.layers["unscaled"].data[:200]


array([2.748392  , 2.117309  , 1.5378077 , 2.117309  , 1.5378077 ,
       1.5378077 , 2.117309  , 1.5378077 , 2.117309  , 2.748392  ,
       4.201385  , 2.117309  , 1.5378077 , 1.23438   , 2.117309  ,
       2.117309  , 2.117309  , 2.117309  , 2.117309  , 2.117309  ,
       1.5378077 , 2.117309  , 3.1322825 , 2.748392  , 2.117309  ,
       1.5378077 , 3.1322825 , 1.5378077 , 2.117309  , 2.117309  ,
       1.0392824 , 2.117309  , 2.117309  , 2.117309  , 2.117309  ,
       2.748392  , 2.748392  , 1.5378077 , 2.117309  , 2.117309  ,
       2.117309  , 1.23438   , 1.5378077 , 1.5378077 , 2.117309  ,
       2.117309  , 2.117309  , 2.117309  , 2.117309  , 2.117309  ,
       2.117309  , 2.117309  , 2.748392  , 2.117309  , 2.117309  ,
       2.117309  , 2.117309  , 1.23438   , 2.117309  , 1.23438   ,
       2.117309  , 2.481829  , 1.5378077 , 0.39693043, 2.117309  ,
       2.117309  , 1.23438   , 2.117309  , 2.117309  , 1.5378077 ,
       1.5378077 , 2.117309  , 1.23438   , 2.117309  , 1.53780

In [19]:
cdata = ad.read_h5ad(r"C:\Users\Orangeeee\Downloads\small_intestine.h5ad")

NameError: name 'ad' is not defined

In [6]:
cdata

AnnData object with n_obs × n_vars = 3514 × 20782
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'cell_id', 'n_genes', 'n_counts', 'leiden', 'umap_density', 'nCount_SCT', 'nFeature_SCT', 'predicted.predicted_celltype.score', 'predicted.predicted_celltype', 'azimuth_label', 'azimuth_score'
    obsm: 'X_ref_pca', 'X_umap_proj'

In [1]:
import scanpy as sc
import os
import pandas as pd

# Path to your data
data_dir = "G:/Secondary_analysis/Organized_by_Tissue/Kidney/"
# Or check the annotated folder specifically:
# data_dir = "F:/12_30_2025_test_azimuth_annotation/annotated/"

# List all h5ad files
files = [f for f in os.listdir(data_dir) if f.endswith('.h5ad')]

report = []

for file_name in files:
    file_path = os.path.join(data_dir, file_name)

    try:
        # read_h5ad(..., backed='r') is extremely fast because it doesn't load the whole matrix
        adata = sc.read_h5ad(file_path, backed='r')

        # Check for the label in obs
        has_label = 'azimuth_label' in adata.obs.columns

        # Check for the projection in obsm
        has_umap = 'X_umap_proj' in adata.obsm.keys()

        report.append({
            "File": file_name,
            "Cells": adata.n_obs,
            "has_label": has_label,
            "has_umap": has_umap
        })
    except Exception as e:
        report.append({"File": file_name, "Error": str(e)})

# Display as a nice table
df_report = pd.DataFrame(report)
print(df_report)

                    File  Cells  has_label  has_umap
0   HBM226.HRTZ.874.h5ad   2752      False     False
1   HBM247.HLXR.494.h5ad   2545       True      True
2   HBM253.ZBGF.863.h5ad   9146       True      True
3   HBM264.MJCH.639.h5ad  20990       True      True
4   HBM292.MTQK.563.h5ad   5805      False     False
..                   ...    ...        ...       ...
73  HBM969.PBMH.689.h5ad   2752       True      True
74  HBM976.LDTR.982.h5ad   3986       True      True
75  HBM976.MRWH.263.h5ad   7897       True      True
76  HBM979.VMDC.365.h5ad  15990       True      True
77  HBM988.XDFD.773.h5ad    382      False     False

[78 rows x 4 columns]


In [2]:
df_report

File  Cells  has_label  has_umap
0   HBM226.HRTZ.874.h5ad   2752      False     False
1   HBM247.HLXR.494.h5ad   2545       True      True
2   HBM253.ZBGF.863.h5ad   9146       True      True
3   HBM264.MJCH.639.h5ad  20990       True      True
4   HBM292.MTQK.563.h5ad   5805      False     False
..                   ...    ...        ...       ...
73  HBM969.PBMH.689.h5ad   2752       True      True
74  HBM976.LDTR.982.h5ad   3986       True      True
75  HBM976.MRWH.263.h5ad   7897       True      True
76  HBM979.VMDC.365.h5ad  15990       True      True
77  HBM988.XDFD.773.h5ad    382      False     False

[78 rows x 4 columns]

In [17]:
import pandas as pd

df = pd.read_parquet(r"E:\UIC_PHD\PythonProject\12-4-2025-Matriviz\data\Heart\HBM296.KZXD.676\HBM296.KZXD.676_v1.parquet")

In [18]:
df

index     umap_1     umap_2  \
0     AACGCGCAGAAAGCCTACGAACCGCAGAATAGTTAACCAT  11.348228   4.762523   
1      AACGCGCAGAAAGCCTACGAACCGCAGAATCGAGGCAAT -11.398079  -3.298662   
2      AACGCGCAGAAAGCCTACGACAACCAGTACATTCGGAGT  -6.395614 -13.235955   
3     AACGCGCAGAAAGCCTACGACAGGAGGAGAAAATCGTTCT   0.939482 -14.270857   
4     AACGCGCAGAAAGCCTACGACAGGAGGAGAATCAATACGT   7.809311   2.640737   
...                                        ...        ...        ...   
3509   TGATTAGGTATTGAGAGAGTCAGGAGGAGACGCTAACCT   1.451226 -14.009255   
3510  TGATTAGGTATTGAGAGAGTCCGCAAGTTCATATCTGGAT   8.184582   3.455465   
3511   TGATTAGGTATTGAGAGAGTCCGCAAGTTCCTACCTGGT   2.246718 -13.235349   
3512   TGATTAGGTATTGAGAGAGTTCTCCTATAACAGATCAGT  -6.603911 -13.075222   
3513  TGATTAGGTATTGAGAGAGTTTATTATGGTAGGATAATCT  -6.507880 -11.286882   

                  azimuth_label  TSPAN6  SCYL3  C1orf112  FGR  FUCA2  GCLC  \
0     Ventricular Cardiomycoyte     0.0    0.0       0.0  0.0    0.0   0.0   
1                    Fibroblast     0.0    0.0       0.0  0.0    0.0   0.0   
2                             B     0.0    0.0       0.0  0.0    0.0   0.0   
3                    Macrophage     0.0    0.0       0.0  0.0    0.0   0.0   
4     Ventricular Cardiomycoyte     0.0    0.0       0.0  0.0    0.0   0.0   
...                         ...     ...    ...       ...  ...    ...   ...   
3509                 Macrophage     0.0    0.0       0.0  0.0    0.0   0.0   
3510  Ventricular Cardiomycoyte     0.0    0.0       0.0  0.0    0.0   0.0   
3511               Monocyte/cDC     0.0    0.0       0.0  0.0    0.0   0.0   
3512                          T     0.0    0.0       0.0  0.0    0.0   0.0   
3513                        ILC     0.0    0.0       0.0  0.0    0.0   0.0   

      ...  AL451136.1  BX255925.4  AL136981.4  AC079772.1  AC118281.1  \
0     ...    0.000000         0.0         0.0         0.0         0.0   
1     ...    0.000000         0.0         0.0         0.0         0.0   
2     ...    0.000000         0.0         0.0         0.0         0.0   
3     ...    0.000000         0.0         0.0         0.0         0.0   
4     ...    0.000000         0.0         0.0         0.0         0.0   
...   ...         ...         ...         ...         ...         ...   
3509  ...    0.000000         0.0         0.0         0.0         0.0   
3510  ...    0.000000         0.0         0.0         0.0         0.0   
3511  ...    0.000000         0.0         0.0         0.0         0.0   
3512  ...    0.000000         0.0         0.0         0.0         0.0   
3513  ...    2.955688         0.0         0.0         0.0         0.0   

      AL109627.1  AC024558.2  AL669830.2  AL357075.4  All_Genes  
0            0.0         0.0         0.0         0.0   0.054899  
1            0.0         0.0         0.0         0.0   0.030507  
2            0.0         0.0         0.0         0.0   0.036683  
3            0.0         0.0         0.0         0.0   0.047271  
4            0.0         0.0         0.0         0.0   0.052204  
...          ...         ...         ...         ...        ...  
3509         0.0         0.0         0.0         0.0   0.038377  
3510         0.0         0.0         0.0         0.0   0.056461  
3511         0.0         0.0         0.0         0.0   0.052610  
3512         0.0         0.0         0.0         0.0   0.044577  
3513         0.0         0.0         0.0         0.0   0.041696  

[3514 rows x 20787 columns]

In [55]:
df1 = pd.read_parquet(r"F:\12_30_2025_test_azimuth_annotation\finished\HBM254.SJWB.835\HBM254.SJWB.835_v1.parquet")

In [56]:
df1

index     umap_1     umap_2               azimuth_label  \
0    AAACGGGAGATATGGT   5.822976  12.082104               NK_CD56bright   
1    AAACGGGGTCATACTG   7.336904   1.118057                 Erythrocyte   
2    AAAGATGTCATCGCTC   2.178029   5.413936                       CD4 T   
3    AAAGCAAAGTTCGCAT   5.144802  -2.997720  Vascual Portal Endothelial   
4    AAATGCCGTGTGACGA  12.913542  -3.720132                      Plasma   
..                ...        ...        ...                         ...   
245  TTGGCAAAGAAGGCCT  -0.731064 -11.616410  Noninflammatory Macrophage   
246  TTTATGCGTCACAAGG  -0.746167 -11.626999  Noninflammatory Macrophage   
247  TTTGCGCAGACTGGGT   5.118172  -2.983406  Vascual Portal Endothelial   
248  TTTGGTTTCTGATTCT   5.749466  12.111567               NK_CD56bright   
249  TTTGTCAGTGAACCTT   9.920386   9.014335                          NK   

     ENSG00000000003.15  ENSG00000000457.14  ENSG00000000460.17  \
0              -0.12549           -0.204045            -0.22071   
1              -0.12549           -0.204045            -0.22071   
2              -0.12549           -0.204045            -0.22071   
3              -0.12549           -0.204045            -0.22071   
4              -0.12549           -0.204045            -0.22071   
..                  ...                 ...                 ...   
245            -0.12549           -0.204045            -0.22071   
246            -0.12549           -0.204045            -0.22071   
247            -0.12549           -0.204045            -0.22071   
248            -0.12549           -0.204045            -0.22071   
249            -0.12549           -0.204045            -0.22071   

     ENSG00000000938.13  ENSG00000001036.14  ENSG00000001084.13  ...  \
0              2.927526            -0.36454           -0.392820  ...   
1             -0.433792            -0.36454           -0.392820  ...   
2             -0.433792            -0.36454           -0.392820  ...   
3             -0.433792            -0.36454           -0.392820  ...   
4             -0.433792            -0.36454           -0.392820  ...   
..                  ...                 ...                 ...  ...   
245            1.827066            -0.36454            2.380367  ...   
246           -0.433792            -0.36454            2.821481  ...   
247           -0.433792            -0.36454           -0.392820  ...   
248           -0.433792            -0.36454           -0.392820  ...   
249           -0.433792            -0.36454           -0.392820  ...   

     ENSG00000288012.1  ENSG00000288044.1  ENSG00000288066.1  \
0            -0.179876          -0.247893          -0.140824   
1            -0.179876          -0.247893          -0.140824   
2            -0.179876          -0.247893          -0.140824   
3            -0.179876          -0.247893          -0.140824   
4            -0.179876          -0.247893          -0.140824   
..                 ...                ...                ...   
245          -0.179876          -0.247893          -0.140824   
246          -0.179876          -0.247893          -0.140824   
247          -0.179876          -0.247893          -0.140824   
248          -0.179876           3.633720          -0.140824   
249          -0.179876          -0.247893          -0.140824   

     ENSG00000288093.1  ENSG00000288208.1  ENSG00000288258.1  \
0            -0.212132          -0.101112          -0.401982   
1            -0.212132          -0.101112          -0.401982   
2            -0.212132          -0.101112          -0.401982   
3            -0.212132          -0.101112          -0.401982   
4            -0.212132          -0.101112          -0.401982   
..                 ...                ...                ...   
245          -0.212132          -0.101112          -0.401982   
246          -0.212132          -0.101112          -0.401982   
247           4.355882          -0.101112          -0.401982   
248          -0.212132          -0.1

In [49]:
edata = ad.read_h5ad(r"F:\12_30_2025_test_azimuth_annotation\HBM254.SJWB.835.h5ad")

In [50]:
fdata = ad.read_h5ad(r"F:\12_30_2025_test_azimuth_annotation\annotated\HBM254.SJWB.835.h5ad")

In [53]:
edata

AnnData object with n_obs × n_vars = 250 × 13626
    obs: 'n_genes', 'n_counts', 'leiden', 'umap_density'
    var: 'hugo_symbol', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'annotation_metadata', 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'umap', 'umap_density_params'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    layers: 'spliced', 'spliced_unspliced_sum', 'unscaled', 'unspliced'
    obsp: 'connectivities', 'distances'

In [54]:
fdata

AnnData object with n_obs × n_vars = 250 × 11607
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'n_genes', 'n_counts', 'leiden', 'umap_density', 'nCount_SCT', 'nFeature_SCT', 'predicted.predicted_celltype.score', 'predicted.predicted_celltype', 'azimuth_label', 'azimuth_score'
    var: 'hugo_symbol'
    obsm: 'X_ref_pca', 'X_umap_proj'

In [58]:
sidata = ad.read_h5ad(r"C:\Users\Orangeeee\Downloads\small_intestine.h5ad")

In [59]:
sidata

AnnData object with n_obs × n_vars = 42036 × 60606
    obs: 'donor_id', 'tissue_in_publication', 'anatomical_position', 'method', 'cdna_plate', 'library_plate', 'notes', 'cdna_well', 'assay_ontology_term_id', 'sample_id', 'replicate', '10X_run', 'ambient_removal', 'donor_method', 'donor_assay', 'donor_tissue', 'donor_tissue_assay', 'cell_type_ontology_term_id', 'compartment', 'broad_cell_class', 'free_annotation', 'manually_annotated', 'published_2022', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ercc', 'pct_counts_ercc', '_scvi_batch', '_scvi_labels', 'scvi_leiden_donorassay_full', 'ethnicity_original', 'scvi_leiden_res05_tissue', 'sample_number', 'suspension_type', 'tissue_type', 'disease_ontology_term_id', 'is_primary_data', 'tissue_ontology_term_id', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'development_stage_ontology_term_id', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'developm